[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"

output_directory = "/Users/yoonha/ITS3/202503KEK_analysis/plots/QA_babyMOSS"
detectors_file = ""
histogram_file = "bb3_QA_analysed_507204824_241215204836.root"

number_of_events = 10000

[Metronome]
triggers=1

[EventLoaderEUDAQ2]
eudaq_loglevel="ERROR"
file_name = "/Users/yoonha/ITS3/202503KEK_analysis/data/run507204824_241215204836.raw"

[ClusteringSpatial]

[Correlations]